config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

resources :posts

  get 'help' => 'help#index'

  get 'about' => 'about#index'

  get 'aboutshow' =>'about#show'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @abouttext = 'This is from the about controller'
  end
  def show
    @aboutshowtext = 'This is from the about show method'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @allposts = Post.all
  end

  def show

  end

  def destroy

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(page_params)
    if @post.save
      redirect_to '/posts'
    else
      render 'new'
    end
  end

  private
  def page_params
    params.require(:post).permit(:posttext, :postauthor)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<% provide(:title, "About") %>
<h1>This is the about page!</h1>
<%= render 'layouts/partial' %>
<p><%= @abouttext %></p>

app/views/about/show.html.erb
<% provide(:title, "About-Show") %>
<p>This is the about show page!</p>
<p><%= @aboutshowtext %></p>

app/views/help/index.html.erb
<h1>Help#index</h1>
<p>Find me in app/views/help/index.html.erb</p>

app/views/layouts/_partial.html.erb
<p>This is a partial from layouts</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> | Firescape</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "Posts") %>
<h1>Posts</h1>
<% @allposts.each  do |post| %>
<%= post.posttext %> <br>
<% end %>

app/views/posts/new.html.erb
<h1>Submit a new post!</h1>
<%= form_for(@post) do |f| %>
<div>
  <%= f.label :'Post Text' %><br>
  <%= f.text_area :posttext %>
  <%= f.text_field :postauthor %>
</div>
<div>
  <%= f.submit 'Create' %>
</div>
<% end %>

app/views/posts/show.html.erb
<% provide(:title, "Posts") %>
<h1>Posts</h1>
<% @allposts.each  do |post| %>
<%= post.posttext %> <br>
<% end %>

app/views/welcome/index.html.erb
<% provide(:title, "Home") %>
<h1>Welcome to my Ruby On Rails Website!</h1>
<p> Go here for the <%= link_to 'about page', about_path %></p>
<p> Click here see all  <%= link_to 'posts!', posts_path %></p>